#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

xsetroot -cursor_name left_ptr

feh --bg-scale /home/nephilim/.wallpapers/takopi-original-sin-2.png
picom &

pkill polybar
polybar mybar &

bspc config border_width         1
bspc config focused_border_color "#ffffff"
bspc config window_gap           10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
